### ISSUE TITLE
Wrong recursive merge of default options.

### ISSUE THREAD

**Issue by rcbitencourt** [TimeoutZero/basebuild-angular#32]
If i override an attribute like an array in my gulpfile conf, it extends the default, but keep another indexes on the attribute, for example:

`var defaults = { test: ["default1"] }`
`var newOptions = { test: [] }`

`_.defaultsDeep(defaults, newOptions) =  returns { test: ["default1"] }`

Another example:

`var defaults = { test: ["default1", "default2] }`
`var newOptions = { test: ["test"] }`

`_.defaultsDeep(defaults, newOptions) =  returns { test: ["test", "default2"] }`

**Comment by carloshpds** [comment]
That's true 😞  . I'm looking for alternatives, please tell me if you have any ideas!

**Comment by carloshpds** [comment]
Maybe a mixin could an option here. Something like this:
```
_.mixin({
  'defaultsDeep': _.partialRight(_.merge, function recursiveDefaults () {
    // Ensure dates and arrays are not recursively merged
    if (_.isArray(arguments[0]) || _.isDate(arguments[0])) {
      return arguments[0];
    }
    return _.merge(arguments[0], arguments[1], recursiveDefaults);
  })
});
````
